//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeEditor.LocalUI", typeof(LocalUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Ingredient.
        /// </summary>
        internal static string AddIngredient {
            get {
                return ResourceManager.GetString("AddIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Recipe.
        /// </summary>
        internal static string AddRecipe {
            get {
                return ResourceManager.GetString("AddRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Ingredient.
        /// </summary>
        internal static string DelIngredient {
            get {
                return ResourceManager.GetString("DelIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Recipe.
        /// </summary>
        internal static string DelRecipe {
            get {
                return ResourceManager.GetString("DelRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        internal static string Ingredients {
            get {
                return ResourceManager.GetString("Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Quantity.
        /// </summary>
        internal static string ProductQuantity {
            get {
                return ResourceManager.GetString("ProductQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore File.
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save on Exit.
        /// </summary>
        internal static string SaveOnExit {
            get {
                return ResourceManager.GetString("SaveOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item.
        /// </summary>
        internal static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (-3s).
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecipeEditor.
        /// </summary>
        internal static string ToolName {
            get {
                return ResourceManager.GetString("ToolName", resourceCulture);
            }
        }
    }
}
